baseURL: https://www.librolibero.eu/
languageCode: en-us
title: LibroLibero.eu
theme: ["PaperMod"]
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  homeInfoParams:
    Title: "Libro Libero"
    Content: >
      - Vogliamo che i libri "liberati" (donati o abbandonati) vengano letti da chiunque ma non che vengano RIVENDUTI sulle bancarelle o che finiscano imprigionati nelle librerie private!

      -   
        
      - Su ogni libro liberato andrebbe attaccata un'etichetta indicando che si tratta di un libro libero! E poi sarebbe bello poter aggiungere il CAP (Codice di Avviamento Postale) del luogo di "partenza", la data di liberazione e possibilmente il nome/sigla/pseudonimo del donatore.

      -
        
      - Stampa le [etichette](/assets/librolibero-eu-v1.pdf)

